package test

var encodeTestcasesBase32 = []testcase{
	{
		module:      "encoding",
		pkg:         "base32",
		tab:         "encode",
		argOperator: "from-text",
		in:          []string{""},
		out:         []string{""},
	},
	{
		module:      "encoding",
		pkg:         "base32",
		tab:         "encode",
		argOperator: "from-text",
		in:          []string{"abcdefghijklmnopqrstuvwxyz0123456789"},
		out:         []string{"MFRGGZDFMZTWQ2LKNNWG23TPOBYXE43UOV3HO6DZPIYDCMRTGQ2TMNZYHE======"},
	},
	{
		module:      "encoding",
		pkg:         "base32",
		tab:         "encode",
		argOperator: "from-text",
		in:          []string{"The quick fox jumps over the lazy dog."},
		out:         []string{"KRUGKIDROVUWG2ZAMZXXQIDKOVWXA4ZAN53GK4RAORUGKIDMMF5HSIDEN5TS4==="},
	},
	{
		module:      "encoding",
		pkg:         "base32",
		tab:         "decode",
		argOperator: "from-text",
		in:          []string{"MFRGGZDFMZTWQ2LKNNWG23TPOBYXE43UOV3HO6DZPIYDCMRTGQ2TMNZYHE======"},
		out:         []string{"abcdefghijklmnopqrstuvwxyz0123456789"},
	},
	{
		module:      "encoding",
		pkg:         "base32",
		tab:         "decode",
		argOperator: "from-text",
		in:          []string{"KRUGKIDROVUWG2ZAMZXXQIDKOVWXA4ZAN53GK4RAORUGKIDMMF5HSIDEN5TS4==="},
		out:         []string{"The quick fox jumps over the lazy dog."},
	},
}

var encodeTestcasesBase64 = []testcase{
	{
		module:      "encoding",
		pkg:         "base64",
		tab:         "encode",
		argOperator: "from-text",
		in:          []string{""},
		out:         []string{""},
	},
	{
		module:      "encoding",
		pkg:         "base64",
		tab:         "encode",
		argOperator: "from-text",
		in:          []string{"abcdefghijklmnopqrstuvwxyz0123456789"},
		out:         []string{"YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU2Nzg5"},
	},
	{
		module:      "encoding",
		pkg:         "base64",
		tab:         "encode",
		argOperator: "from-text",
		in:          []string{"The quick fox jumps over the lazy dog."},
		out:         []string{"VGhlIHF1aWNrIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZy4="},
	},
	{
		module:      "encoding",
		pkg:         "base64",
		tab:         "decode",
		argOperator: "from-text",
		in:          []string{"YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU2Nzg5"},
		out:         []string{"abcdefghijklmnopqrstuvwxyz0123456789"},
	},
	{
		module:      "encoding",
		pkg:         "base64",
		tab:         "decode",
		argOperator: "from-text",
		in:          []string{"VGhlIHF1aWNrIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZy4="},
		out:         []string{"The quick fox jumps over the lazy dog."},
	},
}

var encodeTestcasesHex = []testcase{
	{
		module:      "encoding",
		pkg:         "hex",
		tab:         "encode",
		argOperator: "from-text",
		in:          []string{""},
		out:         []string{""},
	},
	{
		module:      "encoding",
		pkg:         "hex",
		tab:         "encode",
		argOperator: "from-text",
		in:          []string{"abcdefghijklmnopqrstuvwxyz0123456789"},
		out:         []string{"6162636465666768696a6b6c6d6e6f707172737475767778797a30313233343536373839"},
	},
	{
		module:      "encoding",
		pkg:         "hex",
		tab:         "encode",
		argOperator: "from-text",
		in:          []string{"The quick fox jumps over the lazy dog."},
		out:         []string{"54686520717569636b20666f78206a756d7073206f76657220746865206c617a7920646f672e"},
	},
	{
		module:      "encoding",
		pkg:         "hex",
		tab:         "decode",
		argOperator: "from-text",
		in:          []string{"6162636465666768696a6b6c6d6e6f707172737475767778797a30313233343536373839"},
		out:         []string{"abcdefghijklmnopqrstuvwxyz0123456789"},
	},
	{
		module:      "encoding",
		pkg:         "hex",
		tab:         "decode",
		argOperator: "from-text",
		in:          []string{"54686520717569636b20666f78206a756d7073206f76657220746865206c617a7920646f672e"},
		out:         []string{"The quick fox jumps over the lazy dog."},
	},
}

var encodeTestcasesHtml = []testcase{
	{
		module:      "encoding",
		pkg:         "html",
		tab:         "escape",
		argOperator: "from-text",
		in:          []string{""},
		out:         []string{""},
	},
	{
		module:      "encoding",
		pkg:         "html",
		tab:         "escape",
		argOperator: "from-text",
		in:          []string{"<h1>Hello World!</h1>"},
		out:         []string{"&lt;h1&gt;Hello World!&lt;/h1&gt;"},
	},
	{
		module:      "encoding",
		pkg:         "html",
		tab:         "escape",
		argOperator: "from-text",
		in:          []string{"<div><p>The <i>quick</i> fox <b>jumps</b> over the lazy dog.</p></div>"},
		out:         []string{"&lt;div&gt;&lt;p&gt;The &lt;i&gt;quick&lt;/i&gt; fox &lt;b&gt;jumps&lt;/b&gt; over the lazy dog.&lt;/p&gt;&lt;/div&gt;"},
	},
	{
		module:      "encoding",
		pkg:         "html",
		tab:         "unescape",
		argOperator: "from-text",
		in:          []string{"&lt;h1&gt;Hello World!&lt;/h1&gt;"},
		out:         []string{"<h1>Hello World!</h1>"},
	},
	{
		module:      "encoding",
		pkg:         "html",
		tab:         "unescape",
		argOperator: "from-text",
		in:          []string{"&lt;div&gt;&lt;p&gt;The &lt;i&gt;quick&lt;/i&gt; fox &lt;b&gt;jumps&lt;/b&gt; over the lazy dog.&lt;/p&gt;&lt;/div&gt;"},
		out:         []string{"<div><p>The <i>quick</i> fox <b>jumps</b> over the lazy dog.</p></div>"},
	},
}

var encodeTestcasesUri = []testcase{
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "encode-uri",
		argOperator: "from-text",
		in:          []string{""},
		out:         []string{""},
	},
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "encode-uri",
		argOperator: "from-text",
		in:          []string{"https://www.example.com/?pie=π&emoji=😁"},
		out:         []string{"https://www.example.com/?pie=%CF%80&emoji=%F0%9F%98%81"},
	},
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "decode-uri",
		argOperator: "from-text",
		in:          []string{""},
		out:         []string{""},
	},
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "decode-uri",
		argOperator: "from-text",
		in:          []string{"https://www.example.com/?pie=%CF%80&emoji=%F0%9F%98%81"},
		out:         []string{"https://www.example.com/?pie=π&emoji=😁"},
	},
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "encode-uri-component",
		argOperator: "from-text",
		in:          []string{""},
		out:         []string{""},
	},
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "encode-uri-component",
		argOperator: "from-text",
		in:          []string{"hello world!"},
		out:         []string{"hello%20world!"},
	},
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "encode-uri-component",
		argOperator: "from-text",
		in:          []string{"`1234567890-=+_)(*&^%$#@!~"},
		out:         []string{"%601234567890-%3D%2B_)(*%26%5E%25%24%23%40!~"},
	},
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "decode-uri-component",
		argOperator: "from-text",
		in:          []string{""},
		out:         []string{""},
	},
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "decode-uri-component",
		argOperator: "from-text",
		in:          []string{"hello%20world!"},
		out:         []string{"hello world!"},
	},
	{
		module:      "encoding",
		pkg:         "uri",
		tab:         "decode-uri-component",
		argOperator: "from-text",
		in:          []string{"%601234567890-%3D%2B_)(*%26%5E%25%24%23%40!~"},
		out:         []string{"`1234567890-=+_)(*&^%$#@!~"},
	},
}
